/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.crowdflower;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class SubStruct implements org.apache.thrift.TBase<SubStruct, SubStruct._Fields>, java.io.Serializable, Cloneable, Comparable<SubStruct> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SubStruct");

  private static final org.apache.thrift.protocol.TField NUMBERS_FIELD_DESC = new org.apache.thrift.protocol.TField("numbers", org.apache.thrift.protocol.TType.SET, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SubStructStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SubStructTupleSchemeFactory();

  public java.util.Set<java.lang.Integer> numbers; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NUMBERS((short)1, "numbers");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NUMBERS
          return NUMBERS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NUMBERS, new org.apache.thrift.meta_data.FieldMetaData("numbers", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SubStruct.class, metaDataMap);
  }

  public SubStruct() {
  }

  public SubStruct(
    java.util.Set<java.lang.Integer> numbers)
  {
    this();
    this.numbers = numbers;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SubStruct(SubStruct other) {
    if (other.isSetNumbers()) {
      java.util.Set<java.lang.Integer> __this__numbers = new java.util.HashSet<java.lang.Integer>(other.numbers);
      this.numbers = __this__numbers;
    }
  }

  public SubStruct deepCopy() {
    return new SubStruct(this);
  }

  @Override
  public void clear() {
    this.numbers = null;
  }

  public int getNumbersSize() {
    return (this.numbers == null) ? 0 : this.numbers.size();
  }

  public java.util.Iterator<java.lang.Integer> getNumbersIterator() {
    return (this.numbers == null) ? null : this.numbers.iterator();
  }

  public void addToNumbers(int elem) {
    if (this.numbers == null) {
      this.numbers = new java.util.HashSet<java.lang.Integer>();
    }
    this.numbers.add(elem);
  }

  public java.util.Set<java.lang.Integer> getNumbers() {
    return this.numbers;
  }

  public SubStruct setNumbers(java.util.Set<java.lang.Integer> numbers) {
    this.numbers = numbers;
    return this;
  }

  public void unsetNumbers() {
    this.numbers = null;
  }

  /** Returns true if field numbers is set (has been assigned a value) and false otherwise */
  public boolean isSetNumbers() {
    return this.numbers != null;
  }

  public void setNumbersIsSet(boolean value) {
    if (!value) {
      this.numbers = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case NUMBERS:
      if (value == null) {
        unsetNumbers();
      } else {
        setNumbers((java.util.Set<java.lang.Integer>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case NUMBERS:
      return getNumbers();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case NUMBERS:
      return isSetNumbers();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof SubStruct)
      return this.equals((SubStruct)that);
    return false;
  }

  public boolean equals(SubStruct that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_numbers = true && this.isSetNumbers();
    boolean that_present_numbers = true && that.isSetNumbers();
    if (this_present_numbers || that_present_numbers) {
      if (!(this_present_numbers && that_present_numbers))
        return false;
      if (!this.numbers.equals(that.numbers))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetNumbers()) ? 131071 : 524287);
    if (isSetNumbers())
      hashCode = hashCode * 8191 + numbers.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(SubStruct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetNumbers()).compareTo(other.isSetNumbers());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNumbers()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.numbers, other.numbers);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SubStruct(");
    boolean first = true;

    sb.append("numbers:");
    if (this.numbers == null) {
      sb.append("null");
    } else {
      sb.append(this.numbers);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SubStructStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SubStructStandardScheme getScheme() {
      return new SubStructStandardScheme();
    }
  }

  private static class SubStructStandardScheme extends org.apache.thrift.scheme.StandardScheme<SubStruct> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SubStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NUMBERS
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set0 = iprot.readSetBegin();
                struct.numbers = new java.util.HashSet<java.lang.Integer>(2*_set0.size);
                int _elem1;
                for (int _i2 = 0; _i2 < _set0.size; ++_i2)
                {
                  _elem1 = iprot.readI32();
                  struct.numbers.add(_elem1);
                }
                iprot.readSetEnd();
              }
              struct.setNumbersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SubStruct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.numbers != null) {
        oprot.writeFieldBegin(NUMBERS_FIELD_DESC);
        {
          oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.I32, struct.numbers.size()));
          for (int _iter3 : struct.numbers)
          {
            oprot.writeI32(_iter3);
          }
          oprot.writeSetEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SubStructTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SubStructTupleScheme getScheme() {
      return new SubStructTupleScheme();
    }
  }

  private static class SubStructTupleScheme extends org.apache.thrift.scheme.TupleScheme<SubStruct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SubStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetNumbers()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetNumbers()) {
        {
          oprot.writeI32(struct.numbers.size());
          for (int _iter4 : struct.numbers)
          {
            oprot.writeI32(_iter4);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SubStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TSet _set5 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.I32, iprot.readI32());
          struct.numbers = new java.util.HashSet<java.lang.Integer>(2*_set5.size);
          int _elem6;
          for (int _i7 = 0; _i7 < _set5.size; ++_i7)
          {
            _elem6 = iprot.readI32();
            struct.numbers.add(_elem6);
          }
        }
        struct.setNumbersIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

